### ISSUE TITLE
Info to ASN's that are not included in PeeringDB

### ISSUE THREAD

**Issue by NiceRath** [O-X-L/geoip-asn#1]
Some ASN's are not listed in the PeeringDB.
Example: https://geoip.oxl.app/api/asn/398324 | https://risk.oxl.app/api/asn/398324
Would be nice if we could at least get a name/organization for those.

**Comment by superstes** [comment]
Looks like some IP's also do not have an ASN associated in IPInfo - for comparison: https://ipinfo.io/45.181.32.0
