### ISSUE TITLE
[Feature suggestion] IPinfo's IP to Country ASN database

### ISSUE THREAD

**Issue by abdullahdevrel** [O-X-L/geoip-asn#2]
If you would like, you can add country-level data using IPinfo's free IP database: https://ipinfo.io/products/free-ip-database.

Our data is updated daily and provides full accuracy. Also, the included ASN data is based on peering and WHOIS records. Feel free to explore and ping me if you have any questions. Cheers!

**Comment by superstes** [comment]
Updated the readme to recommend users to use IPInfo if the license is acceptable for them.
